[tool.unasyncd]
remove_unused_imports = false
no_cache = false
force_regen = false
add_editors_note = true
exclude = [
    "Something",
    "SomethingElse.within"
]

[tool.unasyncd.files]
    "src/pystuderxcom/api_base_async.py" = "src/pystuderxcom/api_base_sync.py"
    "src/pystuderxcom/discover_async.py" = "src/pystuderxcom/discover_sync.py"
    "src/pystuderxcom/factory_async.py" = "src/pystuderxcom/factory_sync.py"
    "tests/test_api_base_async.py" = "tests/test_api_base_sync.py"
    "tests/test_api_tcp_async.py" = "tests/test_api_tcp_sync.py"
    "tests/test_api_udp_async.py" = "tests/test_api_udp_sync.py"
    "tests/test_api_serial_async.py" = "tests/test_api_serial_sync.py"
    "tests/test_datapoints_async.py" = "tests/test_datapoints_sync.py"
    "tests/test_discover_async.py" = "tests/test_discover_sync.py"
    "tests/test_messageset_async.py" = "tests/test_messageset_sync.py"
    "tests/test_package_async.py" = "tests/test_package_sync.py"
    "example_api_msg_async.py" = "example_api_msg.py"
    "example_discover_devices_async.py" = "example_discover_devices.py"
    "example_discover_moxa_async.py" = "example_discover_moxa.py"
    "example_menu_async.py" = "example_menu.py"

[tool.unasyncd.add_replacements]
    "AsyncXcomApiBase" = "XcomApiBase"
    "AsyncXcomApiTcp" = "XcomApiTcp"
    "AsyncXcomApiUdp" = "XcomApiUdp"
    "AsyncXcomApiSerial" = "XcomApiSerial"
    "AsyncXcomDiscover" = "XcomDiscover"
    "AsyncXcomFactory" = "XcomFactory"
    "aiofiles_open" = "open"
    "asyncio.StreamReader" = "io.BufferedReader"
    "asyncio.StreamWriter" = "io.BufferedWriter"
    "AsyncReader" = "SyncReader"
    "httpx.AsyncClient" = "httpx.Client"
    "asyncudp" = "udp"
    "asyncio.Lock" = "threading.Lock"
    "aclose" = "close"
    "CALL_CONTEXT_ASYNC" = "CALL_CONTEXT_SYNC"
    "pytest_asyncio" = "pytest"
    "AsyncTaskHelper" = "TaskHelper"
    "AsyncTestApi" = "TestApi"
    "AsyncTestClientTcp" = "TestClientTcp"

